version: '3.1'
services:
  catan:
    image: time-series
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  influxdb:
    image:
      influxdb:latest
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_USER=cat-util
      - INFLUXDB_USER_PASSWORD=timeseries
      - INFLUXDB_DB=catutildb
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
